### PR TITLE
feat: move phase2 code out of rust-fil-proofs

### PR DESCRIPTION
**Pull request by cryptonemo**
The phase2 code has been moved here: https://github.com/filecoin-project/filecoin-phase2

When this PR is acceptable and the phase2 repo looks ok, I'll cut a patch release of phase2.

### CODE REVIEW

**Comment by cryptonemo** [comment]
Addresses #1379 by fixing the ignored tests (adds required input file to repo).  This PR also disables building and running of the broken doc tests, but preserves them for reference.

**Comment by dignifiedquire** [comment]
@cryptonemo could you please do the move such that the new repo contains the existing git history? otherwise this looks good to me

**Comment by dignifiedquire** [comment]
useful link: https://ariya.io/2014/07/extracting-parts-of-git-repository-and-keeping-the-history

**Comment by vmx** [comment]
@cryptonemo if you've problems with the "preserve the history", let me know. I've done such things quite a bit in the past (though I also need to google around and look things up, so I probably won't be faster than you doing it yourself :)

**Comment by cryptonemo** [comment]
https://github.com/filecoin-project/filecoin-phase2 is updated.

Does anyone remember how to change the CI to not require jobs that are missing?

**Comment by dignifiedquire** [comment]
> Does anyone remember how to change the CI to not require jobs that are missing?

it is under branch  protection in the settings

**Comment by dignifiedquire** [comment]
@cryptonemo please make sure CI is setup on the new repo

**Comment by cryptonemo** [comment]
CI enabled on new repo.

**Review by dignifiedquire — APPROVED** [review]

**Pull request merged**
