### PR TITLE
test(fil-proofs-tooling): warm up cache for window-post verify

### PR DESCRIPTION
**Pull request by dignifiedquire**

### CODE REVIEW

**Review by vmx — APPROVED** [review]
LGTM, once it's rust fmt'ed correctly.

**Review by cryptonemo — APPROVED** [review]
Looks good, although if we're doing this I'd measure and output the cold verify as well as the warm to get a better picture.

**Comment by dignifiedquire** [comment]
> Looks good, although if we're doing this I'd measure and output the cold verify as well as the warm to get a better picture.

the difference is `1.9s` vs `6ms` on my machine :D

**Comment by cryptonemo** [comment]
> > Looks good, although if we're doing this I'd measure and output the cold verify as well as the warm to get a better picture.
> 
> the difference is `1.9s` vs `6ms` on my machine :D

Yes.  This is information that should be reported in the bench.

**Pull request merged**
