### PR TITLE
fix: ensure that builds without gpu work

### LINKED ISSUE #1346: ensure all code compiles without OpenCL if the `gpu` flag is not enabled

### PR DESCRIPTION
**Pull request by dignifiedquire**
Closes #1346

### CODE REVIEW

**Comment by cryptonemo** [comment]
Is there a CI config *for* GPU tests?

**Comment by dignifiedquire** [comment]
The other builds all enable the `gpu` feature, as it is enabled by default. We don't have proper gpu tests yet on CI, which is a todo for another day.

**Comment by cryptonemo** [comment]
I can't recall the specifics, but when this was first in development, I believe the option to compile out the GPU support was explicitly rejected.  This PR is adding that back, so just wanted to mention it's worth thinking back on why that was, or if it's still relevant.

**Comment by dignifiedquire** [comment]
interesting, I don’t remember that, maybe @porcuquine  can shed some light?

**Comment by porcuquine** [comment]
As I vaguely recall, the first version of GPU support in neptune only exposed the batch hasher API when the GPU feature was enabled. So in order to keep all `rust-fil-proofs` code paths building without even more conditional code, we opted to always build neptune with GPU enabled. If that is no longer needed, I don't think there's a remain reason to require the flag.

**Review by cryptonemo — APPROVED** [review]

**Pull request merged**
