### PR TITLE
refactor: switch to anyhow from failure

### PR DESCRIPTION
**Pull request by dignifiedquire**
First step in preparation for better error handling. 

For some background on different error handling libraries see https://blog.yoshuawuyts.com/error-handling-survey/#libraries

Depends on https://github.com/filecoin-project/merkle_light/pull/54

### CODE REVIEW

**Comment by vmx** [comment]
If this is the first step, what would be the next? I would really like to see us using https://github.com/dtolnay/thiserror only as a next step (which is kind of what I started to prepare at https://github.com/filecoin-project/rust-fil-sector-builder/pull/61).

**Comment by dignifiedquire** [comment]
The next step is use the new infrastructure tho avoid `assert`s, `panic`s and `unwrap`s everyhwere. The reason only `thiserror` is not realistic, is that for a lot of assertions string errors make much more sense, instead of structured errors.

**Comment by dignifiedquire** [comment]
The other part I want to do is to add `.context` to a lot of places, to increase the information detail given

**Comment by vmx** [comment]
The reason I'd prefer `thiserror` over `anyhow` is that you could implement a conversion into a FFI error for each error without the need to do downcasting. If you want to have a simple string based error you could add a new type called something like `GenericError` which will just take a string.

**Comment by vmx** [comment]
@dignifiedquire you might want to fixup the `cleanup` commit locally, so that the CI is passing (it's failing due to the commit linting).

**Comment by dignifiedquire** [comment]
I didn’t change the tests due to time, focusing on user visible changes

**Pull request merged**
