### PR TITLE
[zexe] Batch zigzag [wip]

### PR DESCRIPTION
**Pull request by sanchopansa**

### CODE REVIEW

**Comment by dignifiedquire** [comment]
@sanchopansa @DrPeterVanNostrand @schomatis what is the state of this?

**Comment by schomatis** [comment]
I fixed the parts that I know of inside `fr32.rs`, there are some corrections missing from the `api` module which @sidke was more aware of, but he won't be active in this PR so not sure how to continue, maybe @laser should be able to help.

**Comment by schomatis** [comment]
@sanchopansa The Fr 254-252 resize is being fixed in separate branch https://github.com/filecoin-project/rust-fil-proofs/pull/867, once it's done I'll signal you to merge here (the last changes there are pretty independent from you current work so I think it will be a straightforward operation).

**Comment by dignifiedquire** [comment]
closing we are not using zizag or zexe for now

**Pull request closed without merging**
