### PR TITLE
feat: benchy window-post add parallels tasks

### PR DESCRIPTION
**Pull request by lovel8**
feat: benchy window-post add parallels tasks

### CODE REVIEW

**Comment by vmx** [comment]
Can you please explain a bit more about this feature? Wouldn't it be the same as running benchy manually in parallel?

**Comment by vmx** [comment]
In regards to CI not running. CircleCI is weird. You probably have CircleCI configured to run on the fork you have. In order to get CircleCI run here, you'd need to unfollow your fork in the CircleCI UI.

**Comment by lovel8** [comment]
> Can you please explain a bit more about this feature? Wouldn't it be the same as running benchy manually in parallel?

1. The functions are the same, but it is more convenient to run only one program and run 30 programs at the same time in each concurrent test.
2. The concurrency test runs only one program, which is consistent with the actual business concurrency usage, and the test results are more in line with expectations.

**Comment by lovel8** [comment]
> In regards to CI not running. CircleCI is weird. You probably have CircleCI configured to run on the fork you have. In order to get CircleCI run here, you'd need to unfollow your fork in the CircleCI UI.

image

**Review by vmx — APPROVED** [review]
@cryptonemo can you please also have a look at this PR? It sounds good to me.

**Review by cryptonemo — APPROVED** [review]

**Pull request merged**
