### PR TITLE
feat(storage-proofs): zizag, drgporep and por abstract over the hasher in circuits

### PR DESCRIPTION
**Pull request by dignifiedquire**
Basic tests are passing. Needs some more checks

- make por and drgporep circuits abstract over the hasher
- implement blake2s hasher using blake2s_simd

Ref #531

### CODE REVIEW

**Comment by dignifiedquire** [comment]
@porcuquine this adds the hasher to the parameter identifiers, so I am guessing we have to change parameters versions again?

**Comment by porcuquine** [comment]
Hmmm, if it only changes the set of parameters generated but doesn't change the circuit/parameters for a given identifier, we don't need to bump the version. (The version is needed so we don't find old parameters by the name with which we request new ones.)

But we will need to generate and publish the parameter again. When doing that, remember to clear your cache first, so we don't keep stale parameters around in `parameters.json`.

(It's possible I'm seeing something wrong, so if this sounds mistaken, please flag.)

**Comment by dignifiedquire** [comment]
This is ready to go from my side. Note this will need new params published again, as now the hasher is part of the cache identifier

**Comment by porcuquine** [comment]
Can you include the param publishing in this PR? That would be the best way to do it and should be our policy. Include a comment here stating that you pinned and verified.

**Comment by porcuquine** [comment]
We should see a diff to `parameters.json` in this branch as well (over-explaining because this is new process).

**Comment by porcuquine** [comment]
Looking good, @dignifiedquire. Any chance of extending this to the merklepor example, so we can run that with `--hasher blake2s`?

**Pull request merged**
