### PR TITLE
feat: Use workspace inheritance for dependencies #1645

### PR DESCRIPTION
**Pull request by hanbu97**
Try to pass CI

### CODE REVIEW

**Comment by hanbu97** [comment]
#1645

**Comment by hanbu97** [comment]
CI script for **Test arm with no gpu** using given cargo version **nightly-2022-05-09** not support workspace-inheritance

``` bash
#!/bin/bash -eo pipefail
cargo +nightly-2022-05-09 -Zpackage-features test --release --all --verbose --no-default-features
```

image

**Comment by vmx** [comment]
> CI script for **Test arm with no gpu** using given cargo version **nightly-2022-05-09** not support workspace-inheritance
> 
> ```shell
> 
> ```

I don't think nightly is needed anymore, it might be worth trying out with the same versions the other jobs use. This sounds like a separate PR though. Would you mind opening an issue/PR about it, so that we can track that?

---

In my last comment I forgot to thank you for looking into this, this is surely a bit of work, thanks!

**Comment by vmx** [comment]
This PR was superseded by #1760.

**Pull request closed without merging**
