### PR TITLE
Read trees from GPU within scope of building threads.

### PR DESCRIPTION
**Pull request by porcuquine**
This PR fixes ensure the channels providing the finished subtrees for writing to disk are read within the scope of the threads building the trees. Otherwise, the `rayon::scope` will never complete and writing will hang. This is a regression (vs development of that feature) introduced during the final rebase of #1335. This fix should be merged before #1335 is released, and we should make sure to run lifecycle tests using GPU tree building to exercise it.

### CODE REVIEW

**Comment by porcuquine** [comment]
Looks like this 'fix' now hangs when using CPU – as shown by CI failures. I'll look at it again and push something that succeeds in both cases.

**Comment by porcuquine** [comment]
I don't see this problem locally, rerunning CI to see if it reproduces there.

**Comment by porcuquine** [comment]
If I SSH into the test box and run the test which hangs by itself, it gets through tree building fine (the errors out because of missing parameters).

**Comment by dignifiedquire** [comment]
Manually merged into #1358, which I will merge, as that has passing CI

**Pull request closed without merging**
