### PR TITLE
fix: correct rows_to_discard value during post

### PR DESCRIPTION
**Pull request by cryptonemo**

### CODE REVIEW

**Comment by cryptonemo** [comment]
Requires https://github.com/filecoin-project/merkle_light/pull/89

**Comment by cryptonemo** [comment]
Related to https://github.com/filecoin-project/rust-fil-proofs/issues/1219

**Comment by cryptonemo** [comment]
@porcuquine Can you take a look at https://github.com/filecoin-project/merkle_light/pull/89 as well?  I think the proper way to proceed is to merge that one first, cut a new release for merkle_light, then update this PR to point to that new version.

Separately, we can decide if we need to cut an unplanned proofs release today.  I'm inclined to say no since I have a handle on the issue and it's inefficient, but not breaking as-is, and I'm not entirely sure users of `filecoin-ffi` are ready to consume.

**Comment by porcuquine** [comment]
Yep, I'm looking and have on question (will ask there).

I think it's fine to defer releasing this until the next natural release.

**Comment by cryptonemo** [comment]
Resolves #1219

**Pull request merged**
