### PR TITLE
feat(filecoin-proofs): expose public safe api

### PR DESCRIPTION
**Pull request by dignifiedquire**

### CODE REVIEW

**Comment by dignifiedquire** [comment]
> I strongly believe that the FFI-exposed functions should call this functions, and that these functions should call the `internal.rs` function.

Do we actually need the indirection of `internal.rs` then?

**Comment by laser** [comment]
@dignifiedquire 

> Do we actually need the indirection of internal.rs then?

It was my original intent to turn the `internal.rs` functions into the exported Rust API (which you've now got in `filecoin-proofs/src/api/safe.rs`). So, to answer your question directly: No, I don't think you need the `internal.rs` functions if you have the `safe.rs` functions. You just need to move the guts of `internal.rs` into the `safe.rs` file.

**Comment by laser** [comment]
@dignifiedquire - I can take this PR over if you like, merging `safe.rs` with `internal.rs`. How's that sound?

**Comment by dignifiedquire** [comment]
closing in favor of #684

**Comment by schomatis** [comment]
Doing some house cleaning, going to delete this branch if nobody reclaims it tomorrow (it's showing up in my bunch because I rebased it once and has been my faithful companion ever since).

**Comment by dignifiedquire** [comment]
please do

**Pull request closed without merging**
