### PR TITLE
[WIP] feat(storage-proofs-porep): implement NSE

### PR DESCRIPTION
**Pull request by dignifiedquire**

### CODE REVIEW

**Comment by porcuquine** [comment]
CI is failing. Let's get this branch working completely then keep it in that state (and rebased). It's going to be around for a while as the base into which other NSE work is merged. (cc: @dignifiedquire @keyvank )

**Comment by porcuquine** [comment]
@dignifiedquire Can you rebase this and ensure CI passes when you have a free moment?

**Comment by dignifiedquire** [comment]
> @dignifiedquire Can you rebase this and ensure CI passes when you have a free moment?

rebased

**Comment by porcuquine** [comment]
Thanks. CI seems to have gotten worse.

**Comment by porcuquine** [comment]
We still have conflicts here — probably because we merged the rebased version as a PR (which did not effect a rebase here). I propose to rebase this branch, force-pushing to the head of #1225's branch for simplicity. @cryptonemo @dignifiedquire Any objections?

**Comment by porcuquine** [comment]
Hmm, on further inspection, I think I'm confused and that this just needs another (probably simple) rebase. Sorry, I lost the thread here.

**Comment by dignifiedquire** [comment]
@porcuquine rebased

**Comment by porcuquine** [comment]
CI is broken.

**Comment by porcuquine** [comment]
@keyvank Maybe you can help repair it?

**Comment by cryptonemo** [comment]
No longer needed. Closing PR, but branch/code will remain.

**Pull request closed without merging**
