### PR TITLE
refactor: less mutability, clearer code

### PR DESCRIPTION
**Pull request by vmx**
Make the config configurations more obvious.

### CODE REVIEW

**Comment by cryptonemo** [comment]
Looks ok, but can you manually run the ignored `storage_proofs_update` tests to be sure?  They aren't run on CI due to RAM requirements

**Comment by vmx** [comment]
On `worker-gpu-6` i ran `cargo test -- --ignored`. This is the output:
```
    Finished test [unoptimized + debuginfo] target(s) in 16.31s
     Running unittests src/lib.rs (/home/vmx/rust-fil-proofs/target/debug/deps/storage_proofs_update-0be2ac366c5c14e6)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 5 filtered out; finished in 0.00s

     Running tests/circuit.rs (/home/vmx/rust-fil-proofs/target/debug/deps/circuit-5e0c6a2e24762bbb)

running 1 test
test test_empty_sector_update_constraints_32gib has been running for over 60 seconds
test test_empty_sector_update_constraints_32gib ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 111.23s

     Running tests/circuit_poseidon.rs (/home/vmx/rust-fil-proofs/target/debug/deps/circuit_poseidon-78e5dde7bb5e0d74)

running 1 test
test test_empty_sector_update_constraints_32gib has been running for over 60 seconds
test test_empty_sector_update_constraints_32gib ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 235.78s

     Running tests/compound.rs (/home/vmx/rust-fil-proofs/target/debug/deps/compound-d46bc90f162afbde)

running 6 tests
test test_empty_sector_update_compound_16kib has been running for over 60 seconds
test test_empty_sector_update_compound_1kib has been running for over 60 seconds
test test_empty_sector_update_compound_2kib has been running for over 60 seconds
test test_empty_sector_update_compound_32kib has been running for over 60 seconds
test test_empty_sector_update_compound_4kib has been running for over 60 seconds
test test_empty_sector_update_compound_8kib has been running for over 60 seconds
test test_empty_sector_update_compound_1kib ... ok
test test_empty_sector_update_compound_2kib ... ok
test test_empty_sector_update_compound_4kib ... ok
test test_empty_sector_update_compound_8kib ... ok
test test_empty_sector_update_compound_16kib ... ok
test test_empty_sector_update_compound_32kib ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1518.30s

   Doc-tests storage-proofs-update

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by cryptonemo** [comment]
> On `worker-gpu-6` i ran `cargo test -- --ignored`. This is the output:
> 
> ```
>     Finished test [unoptimized + debuginfo] target(s) in 16.31s
>      Running unittests src/lib.rs (/home/vmx/rust-fil-proofs/target/debug/deps/storage_proofs_update-0be2ac366c5c14e6)
> 
> running 0 tests
> 
> test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 5 filtered out; finished in 0.00s
> 
>      Running tests/circuit.rs (/home/vmx/rust-fil-proofs/target/debug/deps/circuit-5e0c6a2e24762bbb)
> 
> running 1 test
> test test_empty_sector_update_constraints_32gib has been running for over 60 seconds
> test test_empty_sector_update_constraints_32gib ... ok
> 
> test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 111.23s
> 
>      Running tests/circuit_poseidon.rs (/home/vmx/rust-fil-proofs/target/debug/deps/circuit_poseidon-78e5dde7bb5e0d74)
> 
> running 1 test
> test test_empty_sector_update_constraints_32gib has been running for over 60 seconds
> test test_empty_sector_update_constraints_32gib ... ok
> 
> test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 235.78s
> 
>      Running tests/compound.rs (/home/vmx/rust-fil-proofs/target/debug/deps/compound-d46bc90f162afbde)
> 
> running 6 tests
> test test_empty_sector_update_compound_16kib has been running for over 60 seconds
> test test_empty_sector_update_compound_1kib has been running for over 60 seconds
> test test_empty_sector_update_compound_2kib has been running for over 60 seconds
> test test_empty_sector_update_compound_32kib has been running for over 60 seconds
> test test_empty_sector_update_compound_4kib has been running for over 60 seconds
> test test_empty_sector_update_compound_8kib has been running for over 60 seconds
> test test_empty_sector_update_compound_1kib ... ok
> test test_empty_sector_update_compound_2kib ... ok
> test test_empty_sector_update_compound_4kib ... ok
> test test_empty_sector_update_compound_8kib ... ok
> test test_empty_sector_update_compound_16kib ... ok
> test test_empty_sector_update_compound_32kib ... ok
> 
> test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1518.30s
> 
>    Doc-tests storage-proofs-update
> 
> running 0 tests
> 
> test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
> ```

I was staring at that wondering why those times were so awful/slow, but see you ran it in debug mode.  I'm approving, but for my sanity, can you re-run with release mode?

**Review by cryptonemo — APPROVED** [review]

**Comment by vmx** [comment]
```
    Finished release [optimized] target(s) in 30.22s
     Running unittests src/lib.rs (/home/vmx/rust-fil-proofs/target/release/deps/storage_proofs_update-92379a440b6540c9)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 5 filtered out; finished in 0.00s

     Running tests/circuit.rs (/home/vmx/rust-fil-proofs/target/release/deps/circuit-0904a2b3f4e28499)

running 1 test
test test_empty_sector_update_constraints_32gib ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 19.79s

     Running tests/circuit_poseidon.rs (/home/vmx/rust-fil-proofs/target/release/deps/circuit_poseidon-218ebeeb5f635a79)

running 1 test
test test_empty_sector_update_constraints_32gib ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 34.70s

     Running tests/compound.rs (/home/vmx/rust-fil-proofs/target/release/deps/compound-f09b02300967746f)

running 6 tests
test test_empty_sector_update_compound_1kib ... ok
test test_empty_sector_update_compound_2kib ... ok
test test_empty_sector_update_compound_4kib ... ok
test test_empty_sector_update_compound_8kib ... ok
test test_empty_sector_update_compound_16kib has been running for over 60 seconds
test test_empty_sector_update_compound_32kib has been running for over 60 seconds
test test_empty_sector_update_compound_16kib ... ok
test test_empty_sector_update_compound_32kib ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 150.08s

   Doc-tests storage-proofs-update

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Pull request merged**
