### PR TITLE
feat: update rust-toolchain to 1.62.0

### PR DESCRIPTION
**Pull request by cryptonemo**

### CODE REVIEW

**Review by vmx — CHANGES_REQUESTED** [review]
What are the reasons for the upgrade?

I think it should be 1.62.1.

**Comment by cryptonemo** [comment]
> What are the reasons for the upgrade?
> 
> I think it should be 1.62.1.

No particular reason -- we just did a release, so starting the next cycle with the latest toolchain seems reasonable since we'll be testing everything from here.

Please push the update to 1.62.1 if you'd like.

**Comment by vmx** [comment]
> No particular reason -- we just did a release, so starting the next cycle with the latest toolchain seems reasonable since we'll be testing everything from here.

I'd say it's generally good practice in the Rust world to stay on the lowest possible version. But I can see how this produces less work for us.

**Comment by cryptonemo** [comment]
Looks good, but I can't approve my own PR :-)

**Review by vmx — APPROVED** [review]

**Pull request merged**
