### PR TITLE
use anonymous map for aux replication

### PR DESCRIPTION
**Pull request by schomatis**
Builds on top of https://github.com/filecoin-project/rust-fil-proofs/pull/509.

With a zigzag example of size 8192 there doesn't seem to be much difference,

```
# Original:

Total: 309.4 MB
   309.0  99.9%  99.9%    309.0  99.9% ::allocate_in (inline) /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/raw_vec.rs:109
     0.3   0.1% 100.0%      0.3   0.1% ::reserve_internal (inline) /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/raw_vec.rs:683
     0.1   0.0% 100.0%      0.1   0.0% sapling_crypto::jubjub::JubjubBls12::new (inline) ??:0
     0.0   0.0% 100.0%      0.0   0.0% core::ptr::::is_null (inline) /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/ptr.rs:1602

# With `mmap`:

Total: 293.4 MB
   293.0  99.9%  99.9%    293.0  99.9% ::allocate_in (inline) /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/raw_vec.rs:109
     0.3   0.1% 100.0%      0.3   0.1% ::reserve_internal (inline) /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/raw_vec.rs:683
     0.1   0.0% 100.0%      0.1   0.0% sapling_crypto::jubjub::JubjubBls12::new (inline) ??:0
     0.0   0.0% 100.0%      0.0   0.0% core::ptr::::is_null (inline) /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/libcore/ptr.rs:1602
```

(This doesn't include `mmap`'ed memory regions, just the standard `malloc`s.)

~$The next step (in this same PR) will be to port this to the `MerkleTree::from_par_iter` where a much bigger part of the memory is allocated. (Need to figure out how to apply that in https://github.com/filecoin-project/merkle_light/pull/7.)~
(edit: moved that to https://github.com/filecoin-project/rust-fil-proofs/pull/528)

### CODE REVIEW

**Comment by schomatis** [comment]
> works for me, can you clean up your commits so we have one for the mmap and one for the profile changes before merging please?

Actually this is just a WIP not ready to be merged, most of the memory gain is still on the merkle tree generation (that said, we can merge it if you think this is an acceptable gain on its own). As for the other commits, they're from https://github.com/filecoin-project/rust-fil-proofs/pull/509, which is awaiting your review :)

**Comment by dignifiedquire** [comment]
ups, approved the other one :D

**Comment by schomatis** [comment]
Testing https://github.com/filecoin-project/merkle_light/pull/13 in this PR, need to implement the `Element` trait for `Hasher::Domain`.

**Comment by schomatis** [comment]
Hitting a new error now:

```
error[E0599]: no method named `clone` found for type `merkle_light::merkle::MerkleTree<<<Self as layered_drgporep::Layers>::Hasher as hasher::types::Hasher>::Domain, <<Self as layered_drgporep::Layers>::Hasher as hasher::types::Hasher>::Function, merkle_light::merkle::VecStore<<<Self as layered_drgporep::Layers>::Hasher as hasher::types::Hasher>::Domain>>` in the current scope
   --> storage-proofs/src/layered_drgporep.rs:273:44
    |
273 |                         tree_d: aux[layer].clone(),
    |                                            ^^^^^
    |
    = note: the method `clone` exists but the following trait bounds were not satisfied:
            `merkle_light::merkle::MerkleTree<<<Self as layered_drgporep::Layers>::Hasher as hasher::types::Hasher>::Domain, <<Self as layered_drgporep::Layers>::Hasher as hasher::types::Hasher>::Function, merkle_light::merkle::VecStore<<<Self as layered_drgporep::Layers>::Hasher as hasher::types::Hasher>::Domain>> : std::clone::Clone`
```

May be related to https://github.com/rust-lang/rust/issues/19034.

**Comment by schomatis** [comment]
This is already a (small but valid) win on itself, so let's get this merged and leave the MT-internals work for https://github.com/filecoin-project/rust-fil-proofs/pull/529.

**Pull request merged**
