### PR TITLE
Add automatic proxy parameters for paramfetch

### PR DESCRIPTION
**Pull request by ridewindx**

### CODE REVIEW

**Comment by laser** [comment]
@ridewindx - Thanks for the PR. Would you please explain the purpose your changeset? I'm not sure what it does.

**Comment by ridewindx** [comment]
@laser In some area, the default ipfs gateway https://ipfs.io cannot be accessed without a http proxy. This PR use the `env_proxy` crate to automatically detect the environment variable `http_proxy` or `https_proxy` if they have been configured. Just like the way in the http client of Go std library [https://github.com/golang/go/blob/707f3e8c619674444c01b2af4a494732e136dcfd/src/net/http/transport.go#L43].

**Comment by laser** [comment]
@dignifiedquire - Will you review this?

**Comment by dignifiedquire** [comment]
thanks @ridewindx could you please add some documentation about this feature to the binary description? Thanks

**Comment by ridewindx** [comment]
@dignifiedquire have added doc.

**Comment by ridewindx** [comment]
@dignifiedquire have added doc.

**Comment by dignifiedquire** [comment]
thank you

**Comment by dignifiedquire** [comment]
Thank you

**Pull request merged**
