### PR TITLE
Refactor param binaries

### PR DESCRIPTION
**Pull request by DrPeterVanNostrand**
## Changes

- Use `rust-fil-logger` everywhere.
- Changes CLI library from `clap` to `structopt`.
- Use "humanized" sector sizes in user prompts.
- Change all user prompts from `filecoin_proofs::param::choose_from()` to `dialoguer::{MultiSelect, Select}`.

### Commit 7758886 (`fakeipfsadd`)
- Change CLI library.

### Commit e1bd75b (`paramcache`)
- Renames CLI argument from `--params-for-sector-sizes` to `--sector-sizes`
- Manually implements `Clone` for circuits: `StackedCircuit`, SDR `Proof`, `FallbackPoStCircuit`, FallbackPoSt `Sector`
- Manually implementing `Clone` is required because we can't reliably `#[derive(Clone)]` on generic structs having `PhantomData` fields.
- `Clone`-ing circuits makes it so that we don't need to call `::blank_circuit()` every time we need a circuit instance.

### Commit 4627bd1 (`paramfetch`)
- Renames CLI argument from `--params-for-sector-sizes` to `--sector-sizes`
- Changed `ipget` to latest version (`v0.4.0` to `0.6.0`).
- Renamed test file from `fil-proofs-param/tests/paramfetch/prompts_to_fetch.rs` to  `fil-proofs-param/tests/paramfetch/mod.rs`.

### Commit bfb3811 (`parampublish`)
- Rename CLI argument from `--all` to `--list-all` (used for listing all parameter files in the cache dir).
- Add `FileInfo` struct to store a each parameter's: filename, param-id, file extension, and parameter version (so those strings do not have to be repeatedly derived, also makes filtering and sorting easier).
- Add function `is_well_formed_filename()` to ensure that a parameter filename are in the expected format.

### Commit e913a9a
- Remove `filecoin_proofs::param::{choose, choose_from}` in favor of `dialoguer::{MultiSelect, Select}`.

### CODE REVIEW

**Review by cryptonemo — APPROVED** [review]
Looks good

**Review by dignifiedquire — APPROVED** [review]

**Comment by DrPeterVanNostrand** [comment]
Nice, thank you guys for reading through it. If no one has an objection, I am going to rebase this into a single commit before merging (**cc.** @cryptonemo @dignifiedquire)

**Comment by cryptonemo** [comment]
> Nice, thank you guys for reading through it. If no one has an objection, I am going to rebase this into a single commit before merging (**cc.** @cryptonemo @dignifiedquire)

Manually, or using the 'squash and merge'?  I recommend the latter.

**Comment by DrPeterVanNostrand** [comment]
I was going to do a manual rebase, but it doesn't matter. I'll squash and merge.

**Pull request merged**
