### PR TITLE
feat: add script to pin params and publish dnslink

### PR DESCRIPTION
**Pull request by olizilla**
Adds pin-params.sh which will pin the parameters to cluster and publish the cid to proofs.filecoin.io

To keep things simple the script assumes you'll run it against a dir with just the current version of the params in.

It keeps the previous versions of the params about by adding a link to them called `prev` to the new params dir. So you get

```
.
├── v13-proof-of...meta
├── v13-proof-of...params
├── prev
    ├── v12-proof-of...meta
    ├── v12-proof-of...params
    ...
```
and so on. It fetches the old version from the current dnslink at proofs.filecoin.io

The scripts aims to be idempotent... if you re-run it on the same params it wont endlessly re-link the same version of the parms. "same" here means content-addressly the same. If you call two different sets of params v13 then they will all get published. For great permenance.

You need to provide the following env vars

- `CLUSTER_TOKEN` - the basic auth user:pass string to pin things to cluster.ipfs.io
- `DNSIMPLE_TOKEN` - the api key to update the dnslink for proofs.filecoin.io

You need the following tools available on your PATH

- `ipfs-cluster-ctl` - to talk to cluster. download from https://dist.ipfs.io/#ipfs-cluster-ctl
- `npx` - to run dnslink-dnsimple. comes free with npm these days
- `ipfs` - you probably have one of those.

The script will take a while to run. That's expected...
It may redundently re-add the prams to your local ipfs, but thats ~1m on my machine.
Pinning the new params on cluster can take a while. Depends on the prevailing network winds.
Re-running it on the same params is pretty quick, though somewhat redundant.

It's fast and loose with its use of `cut`, so it'll need a little more smarts when your version numbers hit 100.

The storage space needed to store all the params will become an issue for the gateways pretty quickly... we have about 100GB free per node which is supposed to be used to temporarily cache general gateway content. I'll work on a solution for that. Cluster has about 40TB of space, so fill yer boots in that regard.

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Currently testing this out with the v14 params, if that all works we can merge it. Thank you @olizilla

**Comment by olizilla** [comment]
There was an issue trying to link the previous cid when @dignifiedquire ran it. So I have built the v14 params and am running the script now to get them pinned and published, and will see if I can recreate the issue after that by clearing out my local ipfs repo.

**Comment by olizilla** [comment]
It took about 3 hours, but v14 proofs are pinned and published:

```console
$ CLUSTER_TOKEN="user:pass" DNSLINK_TOKEN="xyz" ./pin-params.sh
checking /var/tmp/filecoin-proof-parameters
found v14
adding 25 files to ipfs...
ok! root cid is QmZfxaBMhTXeEVMPKeGAEgK5iD476bcEt7TxW1mr1z3jS8
linking to previous version...
ok! linked cid is QmVpXpoGrMLqT7At58Hm9avkP4HCzPW9SR36BRFzdGBszV
pinning linked cid to cluster...
connect QmUEMvxS2e7iDrereVYc5SWPauXPyNwxcy9BXZrC1QTcHE success
QmVpXpoGrMLqT7At58Hm9avkP4HCzPW9SR36BRFzdGBszV :
    > cluster2             : PINNED | 2019-10-14T11:56:41.286592074Z
    > cluster3             : PINNED | 2019-10-14T11:55:14.286290299Z
    > cluster0             : REMOTE | 2019-10-14T11:22:41.165709028+02:00
    > cluster4             : PINNED | 2019-10-14T11:58:23.148988566Z
    > cluster1             : REMOTE | 2019-10-14T09:22:41.276102388Z
Updated DNSLink on proofs.filecoin.io to dnslink=/ipfs/QmVpXpoGrMLqT7At58Hm9avkP4HCzPW9SR36BRFzdGBszV
done!
```

**Comment by olizilla** [comment]
@dignifiedquire i've run it reliably on 0.4.22 and 0.4.21 with and empty repo, could you try it out again on v14 and share the output? Once it's (re)added the params to ipfs it should be quick as they are already pinned to cluster... i just want to check if it freezes before it manages to calculate the linked cid like it did for you last time.

**Comment by olizilla** [comment]
I pinned the v15 params last night
```console
$ time pin-params.sh 
checking /var/tmp/filecoin-proof-parameters
found v15
adding 25 files to ipfs...
ok! root cid is QmRqRT62He127PaBWendipydzGyYpAp7vvzSDPWredwFYF
linking to previous version...
ok! linked cid is QmasECSrwtj43n1ktsqY3Gizff48my3hVxMSprjNWKZGyB
pinning linked cid to cluster...
connect QmUEMvxS2e7iDrereVYc5SWPauXPyNwxcy9BXZrC1QTcHE success
QmasECSrwtj43n1ktsqY3Gizff48my3hVxMSprjNWKZGyB :
    > cluster2             : REMOTE | 2019-10-28T20:40:26.186656483Z
    > cluster3             : PINNED | 2019-10-29T00:29:23.149791809Z
    > cluster0             : REMOTE | 2019-10-28T21:40:26.101915215+01:00
    > cluster4             : PINNED | 2019-10-29T00:39:17.532744314Z
    > cluster1             : PINNED | 2019-10-29T01:07:36.265779877Z
Updated DNSLink on proofs.filecoin.io to dnslink=/ipfs/QmasECSrwtj43n1ktsqY3Gizff48my3hVxMSprjNWKZGyB
done!
    16131.24 real        29.02 user        34.17 sys
```

**Comment by dignifiedquire** [comment]
going to move this, as @olizilla already has been using this. if it has still issues we can fix them later

**Pull request merged**
