### PR TITLE
refactor: remove storage-proofs sub-crate

### PR DESCRIPTION
**Pull request by DrPeterVanNostrand**
Removes the `storage-proofs` subcrate, but keeps the `storage-proofs-core`, `storage-proofs-porep`, and `storage-proofs-post` subcrates.

### CODE REVIEW

**Review by dignifiedquire — CHANGES_REQUESTED** [review]
CI seems to be unhappy, and I meant moving the subfolders to the top level, probably best if that move happens in its own commit though

**Comment by DrPeterVanNostrand** [comment]
@dignifiedquire np, ill move to the top-level. I'm not sure why the `ensure_groth_parameters_and_keys_linux` ci job is failing

```
#!/bin/bash -eo pipefail
~/paramcache.awesome --params-for-sector-sizes='2048,4096,16384,32768'

error: Found argument '--params-for-sector-sizes' which wasn't expected, or isn't valid in this context

USAGE:
    paramcache.awesome [FLAGS] [OPTIONS]

For more information try --help

Exited with code exit status 1

CircleCI received exit code 1
```

that `paramcache` command works on my local branch

**Comment by cryptonemo** [comment]
> @dignifiedquire np, ill move to the top-level. I'm not sure why the `ensure_groth_parameters_and_keys_linux` ci job is failing
> 
> ```
> #!/bin/bash -eo pipefail
> ~/paramcache.awesome --params-for-sector-sizes='2048,4096,16384,32768'
> 
> error: Found argument '--params-for-sector-sizes' which wasn't expected, or isn't valid in this context
> 
> USAGE:
>     paramcache.awesome [FLAGS] [OPTIONS]
> 
> For more information try --help
> 
> Exited with code exit status 1
> 
> CircleCI received exit code 1
> ```
> 
> that `paramcache` command works on my local branch

Try removing the check (temporarily) that only copies `paramcache.awesome` over if it doesn't exist.  There's a different version there likely, and regardiless, it should be safe to build and copy at any time.

**Comment by cryptonemo** [comment]
CI looks happy now, so you can probably revert that temporary change along with a rebase.

**Review by cryptonemo — APPROVED** [review]
Looks good

**Comment by DrPeterVanNostrand** [comment]
Nice, thank you

**Pull request merged**
