### PR TITLE
fix: remove no longer used exports

### PR DESCRIPTION
**Pull request by vmx**
Use `DefaultOctTree` and `DefaultOctLCTree` instead of `Tree` and `LCTree`.

### CODE REVIEW

**Review by porcuquine — APPROVED** [review]
Needs rebase.

**Comment by vmx** [comment]
Rebased.

**Comment by cryptonemo** [comment]
CI is not happy :-(

**Comment by vmx** [comment]
@cryptonemo yes, I'm on it!

**Comment by vmx** [comment]
CI is happy again.

**Review by cryptonemo — APPROVED** [review]

**Pull request merged**
